version: "2"
services:
  node:
    image: "node:17.8.0"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/ubuntu/discord-bot/v13:/home/node/app
    command: "npm start"
